/**
 * AI layer — provider agnostic (master §57, docs/ai-ext.md).
 *   heuristic : deterministic evidence assembly (default; NOT an LLM)
 *   ollama    : local OpenAI-compatible gateway (health-probed)
 *   openai    : OpenAI-compatible API (server-side key)
 * Structured output only. A failed LLM falls back to the heuristic provider
 * with an explicit label — never a silent "online".
 * The AI explains evidence; canonical market state stays deterministic.
 */
import {
  OLLAMA_URL,
  OPENAI_BASE_URL,
  OPENAI_API_KEY,
  AI_OLLAMA_MODEL,
  AI_OPENAI_MODEL,
  AI_DEFAULT_PROVIDER,
  type AiMode,
} from "../env";
import { eventBus } from "../events";
import type { AnalysisBundle } from "../analysis/bundle";
import { MTF_ROLE_TF, type MtfResult } from "../analysis/mtf";
import type { PsychologySummary } from "../psychology/engine";

/* ------------------------------------------------------------------ types */
export interface AiAnnotation {
  kind: string;
  direction?: string;
  price: number;
  t: number;
}

export interface AiResponse {
  summary: string;
  /**
   * long/short = asserted stance · neutral = NO STANCE on AVAILABLE evidence
   * (PARTIAL/CONFLICT) · unavailable = the MTF evidence is UNAVAILABLE /
   * INSUFFICIENT / STALE, so no stance CAN be taken (absolute-final: was
   * folded into "neutral") · reject = a risk block is active.
   */
  direction: "long" | "short" | "neutral" | "reject" | "unavailable";
  /**
   * 0..100 score, NOT a probability (§11); null when not produced (never a
   * substituted default). Provenance in `semantics.score_provenance`.
   */
  score: number | null;
  thesis: string;
  market_story: string;
  setup_quality: "high" | "medium" | "low" | "none";
  invalidation: string;
  confluences: string[];
  contradictions: string[];
  risks: string[];
  /** 0..100 self-reported by an LLM provider; null when not produced (the heuristic produces none) */
  confidence: number | null;
  /**
   * provider-written evidence text: AI INTERPRETATION for LLM providers
   * (unverified), engine facts for the heuristic — see `semantics`
   */
  evidence: string[];
  /** FACTUAL TECHNICAL EVIDENCE: generated by the engine from the snapshot-identified bundles, never by a provider */
  factual_evidence: string[];
  semantics: AiSemantics;
  annotations: AiAnnotation[];
  missing_data: string[];
  risk_notes: string[];
  strategy_alignment: string;
  psychology_context: string;
  fundamental_context: string;
  /**
   * SOURCE time of the evidence (epoch ms): the oldest MTF component's
   * last-closed-bar close instant. null when unknown — never replaced by the
   * compute/reply time (Task 09, AI-2/AI-3).
   */
  data_timestamp: number | null;
  provider: string;
  model: string;
  latency_ms: number;
  status: "ok" | "fallback" | "error";
}

/**
 * Separates FACTUAL TECHNICAL EVIDENCE (engine output with snapshot identity)
 * from AI INTERPRETATION (provider- or heuristic-layer judgement).
 */
export interface AiSemantics {
  factual_fields: readonly string[];
  interpretation_fields: readonly string[];
  /** `evidence` is engine text for the heuristic, provider text for an LLM */
  evidence_origin: "ENGINE" | "PROVIDER_INTERPRETATION";
  score_provenance: "ENGINEERING_DEFINED_UNCALIBRATED" | "PROVIDER_SELF_REPORTED_UNCALIBRATED" | "NOT_PRODUCED";
  score_basis: string;
  confidence_provenance: "PROVIDER_SELF_REPORTED_UNCALIBRATED" | "NOT_PRODUCED";
  /**
   * Calibration status of `score` / `confidence`: no outcome study maps them
   * to realised frequencies, so any produced number is CALIBRATION_UNVERIFIED.
   * NOT_APPLICABLE only when neither was produced. Never "CALIBRATED".
   */
  calibration: "CALIBRATION_UNVERIFIED" | "NOT_APPLICABLE";
}

export const AI_FACTUAL_FIELDS = ["factual_evidence", "data_timestamp"] as const;
export const AI_INTERPRETATION_FIELDS = [
  "summary", "direction", "score", "thesis", "market_story", "setup_quality", "invalidation", "confluences",
  "contradictions", "risks", "confidence", "evidence", "annotations", "strategy_alignment", "psychology_context",
] as const;

/** heuristic score constants: ENGINEERING_DEFINED, uncalibrated, no source */
export const HEURISTIC_SCORE_BY_VERDICT = { ALIGNED: 62, PARTIAL: 48, CONFLICT: 25 } as const;

export interface AiEvidence {
  symbol: string;
  /**
   * timeframe the CALLER asked about. The evidence itself is always the core
   * MTF hierarchy (macro 4h / context 1h / trigger 15m); see
   * `analyzed_timeframes`. Summaries name the analyzed timeframes, never the
   * requested one as if it had been analyzed (Task 09, AI-1).
   */
  timeframe: string;
  mtf: MtfResult;
  macro: AnalysisBundle | null;
  context: AnalysisBundle | null;
  trigger: AnalysisBundle | null;
  psychology: PsychologySummary;
  risk: { verdict: string; reasons: string[] } | null;
  strategy: { id: string; pass: boolean; reasons: string[] } | null;
  fundamental: string | null;
  data_timestamp: number | null;
  window: { t_min: number; t_max: number; price_min: number; price_max: number };
}

export interface AiResult {
  provider_used: string;
  model: string;
  label: "HEURISTIC MODE · NOT AN LLM" | "OLLAMA" | "OPENAI" | "HEURISTIC FALLBACK · LLM FAILED";
  response: AiResponse;
  error: string | null;
}

/**
 * Honest provider health lifecycle (never optimistic):
 *   NOT_CONFIGURED - no base URL / key in env
 *   CONNECTING     - configured, no probe result yet this process
 *   ONLINE         - last probe reached the provider AND the configured model
 *                    was present in its catalogue
 *   DEGRADED       - provider reachable but the configured model was NOT in
 *                    its catalogue (calls may still work; we do not claim it)
 *   ERROR          - last probe failed (network/timeout/HTTP), reason attached
 */
export type AiHealthState =
  | "NOT_CONFIGURED"
  | "CONFIGURED"
  | "CONNECTING"
  | "ONLINE"
  | "DEGRADED"
  | "ERROR";

export interface ProviderStatusRow {
  id: "heuristic" | "ollama" | "openai";
  configured: boolean;
  online: boolean | null; // null = not probed yet
  /** honest lifecycle state; `online` kept for existing consumers */
  state: AiHealthState;
  latency_ms: number | null;
  model: string | null;
  /** was the configured model present in the provider catalogue? null = unknown */
  model_available: boolean | null;
  models_count: number | null;
  probed_at_ms: number | null;
  error: string | null;
}

/* ------------------------------------------------------- structured checks */
/** finite number clamped into [lo, hi]; null when absent/non-numeric — no substituted default */
function clampOrNull(v: unknown, lo: number, hi: number): number | null {
  if (v === null || v === undefined || v === "") return null;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) ? Math.min(hi, Math.max(lo, n)) : null;
}
function asStringList(v: unknown): string[] {
  return Array.isArray(v) ? v.filter((x) => typeof x === "string").slice(0, 20) : [];
}
function asString(v: unknown, fb = ""): string {
  return typeof v === "string" ? v.slice(0, 2000) : fb;
}

/** Validate + normalize a parsed LLM JSON into the canonical response. */
export function coerceAiResponse(raw: unknown, provider: string, model: string, latency_ms: number, fallbackDirection: "long" | "short" | "neutral", dataTimestamp: number | null = null): AiResponse | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  // "neutral" is a VALID stance (it means: no setup asserted). Rejecting it
  // here used to mislabel a perfectly good completion as "LLM FAILED", which
  // is exactly the kind of dishonest status this codebase forbids.
  const isDir = (v: unknown): v is AiResponse["direction"] =>
    v === "long" || v === "short" || v === "neutral" || v === "reject";
  const direction: AiResponse["direction"] = isDir(r.direction)
    ? r.direction
    : isDir(r.verdict)
      ? r.verdict
      : fallbackDirection;
  const base: AiResponse = {
    summary: asString(r.summary, ""),
    direction,
    score: clampOrNull(r.score, 0, 100),
    thesis: asString(r.thesis),
    market_story: asString(r.market_story),
    setup_quality: ["high", "medium", "low", "none"].includes(asString(r.setup_quality)) ? (asString(r.setup_quality) as AiResponse["setup_quality"]) : "none",
    invalidation: asString(r.invalidation),
    confluences: asStringList(r.confluences),
    contradictions: asStringList(r.contradictions),
    risks: asStringList(r.risks),
    confidence: clampOrNull(r.confidence, 0, 100),
    evidence: asStringList(r.evidence),
    // filled by the caller from the engine bundles (runAi) — never from the provider
    factual_evidence: [],
    annotations: [],
    missing_data: asStringList(r.missing_data),
    risk_notes: asStringList(r.risk_notes),
    strategy_alignment: asString(r.strategy_alignment),
    psychology_context: asString(r.psychology_context),
    fundamental_context: asString(r.fundamental_context),
    // the evidence's source time, NOT the reply time (Task 09, AI-2)
    data_timestamp: dataTimestamp,
    provider,
    model,
    latency_ms,
    status: "ok",
    semantics: {
      factual_fields: AI_FACTUAL_FIELDS,
      interpretation_fields: AI_INTERPRETATION_FIELDS,
      evidence_origin: "PROVIDER_INTERPRETATION",
      score_provenance: clampOrNull(r.score, 0, 100) === null ? "NOT_PRODUCED" : "PROVIDER_SELF_REPORTED_UNCALIBRATED",
      score_basis: "provider self-report; not calibrated, not a probability",
      confidence_provenance: clampOrNull(r.confidence, 0, 100) === null ? "NOT_PRODUCED" : "PROVIDER_SELF_REPORTED_UNCALIBRATED",
      calibration: clampOrNull(r.score, 0, 100) === null && clampOrNull(r.confidence, 0, 100) === null ? "NOT_APPLICABLE" : "CALIBRATION_UNVERIFIED",
    },
  };
  if (base.score === null) base.missing_data.push("score not provided by the provider (left null, not defaulted)");
  return base;
}

/** Geometry validation: annotations must lie inside the analyzed window. */
export function validateAnnotations(ann: unknown[], win: AiEvidence["window"]): { kept: AiAnnotation[]; dropped: number } {
  const kept: AiAnnotation[] = [];
  let dropped = 0;
  const pricePad = (win.price_max - win.price_min) * 0.03 || 1;
  const tPad = (win.t_max - win.t_min) * 0.03 || 1;
  for (const a of ann) {
    if (!a || typeof a !== "object") { dropped++; continue; }
    const x = a as Record<string, unknown>;
    const price = Number(x.price), t = Number(x.t);
    const kind = typeof x.kind === "string" ? x.kind : "";
    if (!Number.isFinite(price) || !Number.isFinite(t)) { dropped++; continue; }
    if (price < win.price_min - pricePad || price > win.price_max + pricePad || t < win.t_min - tPad || t > win.t_max + tPad) { dropped++; continue; }
    kept.push({ kind, price, t, direction: typeof x.direction === "string" ? x.direction : undefined });
  }
  return { kept, dropped };
}

/* ------------------------------------------------------------- providers */
/** the timeframes the evidence actually describes (core MTF hierarchy) */
export function analyzedTimeframes(): { macro: string; context: string; trigger: string } {
  return { ...MTF_ROLE_TF };
}

/**
 * Deterministic evidence read. PURE: never mutates `ev` or its bundles
 * (tests/team09-decision-consumer.test.ts deep-compares before/after).
 * Direction/score/confidence here are AI-LAYER outputs (master §11/§57),
 * derived only from the MTF verdict; they are not Team 02 evidence.
 */
/**
 * FACTUAL TECHNICAL EVIDENCE lines, generated only from engine output (each
 * bundle's timeframe, as-of bar, freshness, fingerprint). Provider-independent.
 */
export function factualEvidence(ev: AiEvidence): string[] {
  const t = ev.trigger;
  const st = t?.structure;
  const indicators = t?.indicators;
  const evidence: string[] = [
    `series bars macro/context/trigger: ${ev.macro?.bars ?? 0}/${ev.context?.bars ?? 0}/${t?.bars ?? 0}`,
  ];
  if (indicators) evidence.push(`rsi14=${fmt(indicators.rsi14)} ema20=${fmt(indicators.ema20)} ema50=${fmt(indicators.ema50)} atr14%=${fmt(indicators.atr14_pct)}`);
  if (st) evidence.push(`trend=${st.trend} (${st.reason})`);
  if (t) evidence.push(`trigger ${t.timeframe} as_of_t=${t.as_of_t ?? "—"} freshness=${t.provenance.freshness} fingerprint=${t.provenance.input_fingerprint}`);
  if (ev.psychology.sections) {
    const fs = ev.psychology.sections.find((s) => s.key === "funding");
    if (fs?.value !== undefined && fs.value !== null) evidence.push(`funding=${fs.value}`);
    const ls = ev.psychology.sections.find((s) => s.key === "liquidation_pressure");
    if (ls) evidence.push(`liquidation data: ${ls.state} — ${ls.reason}`);
  }
  return evidence;
}

export function heuristicAnalyze(ev: AiEvidence): AiResponse {
  const t = ev.trigger;
  const verdict = resolveHeuristicDirection(ev.mtf);
  const st = t?.structure;
  const evidence = factualEvidence(ev);
  const contradictions = ev.psychology.sections
    .filter((s) => s.state === "UNAVAILABLE" || s.verdict === "UNVERIFIED")
    .map((s) => `${s.label}: ${s.state} (${s.reason ?? s.verdict})`);
  const missing = ev.psychology.sections.filter((s) => s.state === "UNAVAILABLE" || s.state === "INSUFFICIENT_DATA").map((s) => s.label);
  if (!t || t.bars < 100) missing.push("trigger history");

  let riskNotes = ev.risk ? ev.risk.reasons.slice(0, 3) : [];
  if (ev.risk?.verdict === "block") riskNotes = ["RISK BLOCK ACTIVE — AI cannot override", ...riskNotes];
  const score = deterministicScore(ev.mtf);
  const tfs = analyzedTimeframes();
  const trigTf = t?.timeframe ?? tfs.trigger;
  const reqNote = ev.timeframe !== trigTf ? ` (requested ${ev.timeframe})` : "";
  return {
    summary: `${ev.symbol} MTF ${tfs.macro}/${tfs.context}/${tfs.trigger}${reqNote}: ${verdict} (score ${score ?? `not produced: MTF ${ev.mtf.verdict}`})`,
    direction: verdict,
    score,
    thesis: heuristicThesis(ev.mtf, ev.psychology),
    market_story: `4H ${ev.macro?.structure.trend ?? "n/a"} · 1H ${ev.context?.structure.trend ?? "n/a"} · 15M ${st?.trend ?? "n/a"} — ${ev.mtf.reason}`,
    setup_quality: score === null ? "none" : score >= 70 ? "medium" : score >= 55 ? "low" : "none",
    // factual structural reference only — the engine does not know a position
    // (Task 09, AI-6); a stop/invalidation policy is not Team 02 output
    invalidation: st?.last_choch
      ? `structural reference: last ${trigTf} CHoCH ${st.last_choch.direction} broke ${fmt(st.last_choch.price)} at bar t=${st.last_choch.t} (not a position-relative stop)`
      : "not defined by structure",
    confluences: evidence.slice(0, 6),
    contradictions,
    risks: [],
    // the heuristic has no confidence model: not produced (was a copy of score)
    confidence: null,
    evidence,
    factual_evidence: evidence,
    // OPEN gaps only — a mitigated (historical) FVG is not current context (AI-5)
    annotations: (st?.fvgs ?? []).filter((f) => f.mitigated_index === null).map((f) => ({ kind: "fvg" as const, direction: f.direction, price: f.direction === "up" ? f.top : f.bottom, t: f.t })).slice(-3),
    missing_data: missing,
    risk_notes: riskNotes,
    strategy_alignment: ev.strategy ? (ev.strategy.pass ? `strategy ${ev.strategy.id} PASS` : `strategy ${ev.strategy.id} not passed: ${ev.strategy.reasons.slice(0, 2).join("; ")}`) : "no live strategy evaluated",
    psychology_context: `bias=${ev.psychology.bias} — ${ev.psychology.bias_reason}`,
    fundamental_context: ev.fundamental ?? "no fundamental context configured",
    data_timestamp: ev.data_timestamp,
    provider: "heuristic",
    model: "heuristic-v1",
    latency_ms: 0,
    status: "ok",
    semantics: {
      factual_fields: AI_FACTUAL_FIELDS,
      interpretation_fields: AI_INTERPRETATION_FIELDS,
      evidence_origin: "ENGINE",
      score_provenance: score === null ? "NOT_PRODUCED" : "ENGINEERING_DEFINED_UNCALIBRATED",
      score_basis: score === null
        ? `MTF verdict ${ev.mtf.verdict} is not scored (insufficient/stale/unavailable evidence is not a score of 0)`
        : `constant per MTF verdict (ALIGNED 62 / PARTIAL 48 / CONFLICT 25): ENGINEERING_DEFINED, uncalibrated, not a probability`,
      confidence_provenance: "NOT_PRODUCED",
      calibration: score === null ? "NOT_APPLICABLE" : "CALIBRATION_UNVERIFIED",
    },
  };
}

/** MTF evidence that cannot support ANY stance (not the same as "no stance") */
export function mtfEvidenceUnavailable(mtf: MtfResult): boolean {
  return mtf.verdict === "UNAVAILABLE" || mtf.verdict === "INSUFFICIENT" || mtf.verdict === "STALE";
}

function resolveHeuristicDirection(mtf: MtfResult): "long" | "short" | "neutral" | "unavailable" {
  // explicit on both sides: a null/neutral bias can never become "short" (AI-4)
  if (mtfEvidenceUnavailable(mtf)) return "unavailable"; // unavailable ≠ neutral
  if (mtf.verdict === "ALIGNED" && mtf.macro_bias === "long") return "long";
  if (mtf.verdict === "ALIGNED" && mtf.macro_bias === "short") return "short";
  return "neutral"; // PARTIAL / CONFLICT / ALIGNED-neutral = no stance on available evidence
}

function deterministicScore(mtf: MtfResult): number | null {
  // ENGINEERING_DEFINED constants, NOT a calibrated probability (master §11).
  // INSUFFICIENT / STALE / UNAVAILABLE evidence is not scored: null, never 0.
  if (mtf.verdict === "ALIGNED" || mtf.verdict === "PARTIAL" || mtf.verdict === "CONFLICT") return HEURISTIC_SCORE_BY_VERDICT[mtf.verdict];
  return null;
}

function heuristicThesis(mtf: MtfResult, psych: PsychologySummary): string {
  if (mtf.verdict === "ALIGNED" && mtf.macro_bias !== "neutral") {
    return `All core timeframes aligned ${mtf.macro_bias}. Psychology neutral; liquidation metrics unavailable — no crowding assertion.`;
  }
  return `Timeframes not aligned (${mtf.verdict}: ${mtf.reason}). Psychology bias neutral (${psych.bias_reason}). No opportunity asserted.`;
}

/**
 * Significant-digit formatting (Task 09): the previous fixed 1–2 decimals
 * rendered sub-cent prices (e.g. 0.00012) as "0.00" — false evidence text.
 */
function fmt(v: number | null | undefined): string {
  return v === null || v === undefined || !Number.isFinite(v) ? "—" : String(Number(v.toPrecision(6)));
}

/* ------------------------------------------------------------- router */
const LLM_TIMEOUT_MS = 60_000;

export async function runAi(ev: AiEvidence, mode: AiMode = AI_DEFAULT_PROVIDER): Promise<AiResult> {
  eventBus.emit("ai.state", { state: "RUNNING", provider: mode });
  const started = Date.now();
  const attempts: { provider: string; online: boolean }[] = [];

  // deterministic fallback always available
  const fallback = (): AiResult => {
    const r = heuristicAnalyze(ev);
    return { provider_used: "heuristic", model: "heuristic-v1", label: "HEURISTIC MODE · NOT AN LLM", response: r, error: null };
  };

  const tryLlm = async (kind: "ollama" | "openai"): Promise<AiResult | null> => {
    const base = kind === "ollama" ? OLLAMA_URL.replace(/\/+$/, "") : OPENAI_BASE_URL.replace(/\/+$/, "");
    const key = kind === "openai" ? OPENAI_API_KEY : "";
    const model = kind === "ollama" ? AI_OLLAMA_MODEL : AI_OPENAI_MODEL;
    const online = await probeProvider(kind);
    attempts.push({ provider: kind, online });
    if (!online) return null;
    const url = `${base}/chat/completions`;
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), LLM_TIMEOUT_MS);
    try {
      // The schema MUST be stated explicitly: `response_format: json_object`
      // only guarantees valid JSON, not the shape. Without this, providers
      // legitimately return `{}` and we would report an empty analysis.
      const sys = [
        "You are AsA, an advisory crypto analysis assistant.",
        "You reason ONLY over the evidence object supplied by the user message.",
        "Never invent metrics, prices, or levels that are not present in the evidence.",
        "If the evidence does not support a directional stance, answer with direction \"neutral\" and explain why — that is a valid, expected answer.",
        "AsA is advisory only and never executes trades; never phrase output as an instruction to place an order.",
        "Reply with a single JSON object using EXACTLY these keys:",
        '{"direction":"long|short|neutral|reject","score":0-100,"confidence":0-100,',
        '"summary":"one sentence","thesis":"2-4 sentences","market_story":"how the timeframes line up",',
        '"setup_quality":"high|medium|low|none","invalidation":"what would falsify this",',
        '"confluences":["..."],"contradictions":["..."],"risks":["..."],"evidence":["cite the evidence fields you used"],',
        '"missing_data":["..."],"risk_notes":["..."],"strategy_alignment":"...","psychology_context":"...","fundamental_context":"..."}',
        "Every string field must be non-empty. score is a deterministic-style score, NOT a probability.",
      ].join(" ");
      const user = JSON.stringify({ task: "structure_analysis", symbol: ev.symbol, timeframe: ev.timeframe, evidence: serializeEvidence(ev) });
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json", ...(key ? { Authorization: `Bearer ${key}` } : {}) },
        body: JSON.stringify({
          model,
          messages: [
            { role: "system", content: sys },
            { role: "user", content: user },
          ],
          response_format: { type: "json_object" },
          temperature: 0.2,
          stream: false,
        }),
        signal: ctrl.signal,
      });
      if (!res.ok) {
        const txt = await res.text().catch(() => "");
        throw new Error(`provider HTTP ${res.status} ${txt.slice(0, 120)}`);
      }
      const data = (await res.json()) as { choices?: { message?: { content?: string } }[] };
      const content = data.choices?.[0]?.message?.content;
      if (!content) throw new Error("empty completion");
      const parsed = JSON.parse(content) as unknown;
      const latency = Date.now() - started;
      const coerced = coerceAiResponse(parsed, kind, model, latency, "neutral", ev.data_timestamp);
      if (!coerced) throw new Error("structured output failed validation");
      // Guard against a syntactically valid but substantively empty answer
      // (e.g. "{}"): reporting that as an LLM analysis would be dishonest.
      if (!coerced.summary.trim() && !coerced.thesis.trim() && coerced.evidence.length === 0) {
        throw new Error("provider returned an empty analysis (no summary/thesis/evidence)");
      }
      // enforce deterministic hard rules (master §57 / ai-ext):
      // factual evidence always comes from the engine, never from the provider
      coerced.factual_evidence = factualEvidence(ev);
      // a provider can never take a stance the evidence cannot support:
      // unavailable/insufficient/stale MTF evidence → "unavailable" (was
      // "neutral" for thin macro history — unavailable is not neutral)
      if (mtfEvidenceUnavailable(ev.mtf) || (ev.macro && ev.macro.bars < 100)) coerced.direction = "unavailable";
      if (ev.risk?.verdict === "block") coerced.direction = "reject";
      const rawAnn = parsed && typeof parsed === "object" ? (parsed as Record<string, unknown>).annotations : undefined;
      const annList = Array.isArray(rawAnn) ? (rawAnn as unknown[]) : [];
      const geo = validateAnnotations(annList, ev.window);
      coerced.annotations = geo.kept;
      if (geo.dropped > 0) coerced.contradictions.push(`annotation geometry: ${geo.dropped} dropped outside window`);
      return { provider_used: kind, model, label: kind === "ollama" ? "OLLAMA" : "OPENAI", response: coerced, error: null };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { provider_used: kind, model, label: "HEURISTIC FALLBACK · LLM FAILED", response: heuristicAnalyze(ev), error: msg };
    } finally {
      clearTimeout(timer);
    }
  };

  let result: AiResult;
  if (mode === "ollama") result = (await tryLlm("ollama")) ?? fallback();
  else if (mode === "openai") result = (await tryLlm("openai")) ?? fallback();
  else if (mode === "heuristic") result = fallback();
  else {
    // auto: local -> cloud -> heuristic
    result = (await tryLlm("ollama")) ?? (await tryLlm("openai")) ?? fallback();
  }
  eventBus.emit("ai.state", { state: "IDLE", provider: result.provider_used });
  return result;
}

/**
 * The evidence object an LLM sees (Task 09, AI-7). Every technical value
 * travels with its timeframe, as-of bar, freshness, validity status and
 * snapshot fingerprint, so the model cannot mistake unavailable for neutral,
 * a historical event for an active one, or a live stat for a closed-bar value.
 */
export function serializeEvidence(ev: AiEvidence): unknown {
  return {
    symbol: ev.symbol,
    requested_timeframe: ev.timeframe,
    analyzed_timeframes: analyzedTimeframes(),
    data_timestamp_ms: ev.data_timestamp,
    semantics: "technical evidence only; null = unavailable (see *_status), never neutral; events are historical facts as of their bar; stats are a live venue snapshot, not closed-bar values",
    mtf: {
      verdict: ev.mtf.verdict, macro_bias: ev.mtf.macro_bias, context_bias: ev.mtf.context_bias, trigger_bias: ev.mtf.trigger_bias, reason: ev.mtf.reason,
      as_of_ms: ev.mtf.as_of_ms, freshness_verified: ev.mtf.freshness_verified, derived_components: ev.mtf.derived_components,
      components: ev.mtf.components.map((c) => ({ role: c.role, timeframe: c.timeframe, state: c.state, bars: c.bars, as_of_t: c.as_of_t, knowable_at_ms: c.knowable_at_ms, freshness: c.freshness, input_fingerprint: c.input_fingerprint })),
    },
    macro: bundleSlice(ev.macro),
    context: bundleSlice(ev.context),
    trigger: bundleSlice(ev.trigger),
    psychology: { bias: ev.psychology.bias, sections: ev.psychology.sections.map((s) => ({ key: s.key, state: s.state, verdict: s.verdict, value: s.value, reason: s.reason })) },
    risk: ev.risk,
    strategy: ev.strategy,
    fundamental: ev.fundamental,
  };
}

export function bundleSlice(b: AnalysisBundle | null): unknown {
  if (!b) return null;
  const p = b.provenance;
  return {
    symbol: b.symbol,
    timeframe: b.timeframe,
    bars: b.bars,
    as_of_t: b.as_of_t,
    last_close: b.last_close,
    provenance: {
      source_ts_ms: p.source_ts_ms, freshness: p.freshness, data_age_ms: p.data_age_ms, closed_bars_only: p.closed_bars_only,
      native: p.native, derived_source_tf: p.derived_source_tf ?? null, engines: p.engines, input_fingerprint: p.input_fingerprint,
    },
    indicators: b.indicators,
    indicator_status: b.indicator_status,
    structure: {
      trend: b.structure.trend, reason: b.structure.reason, trend_evidence: b.structure.trend_evidence,
      last_bos: b.structure.last_bos, last_choch: b.structure.last_choch, sr_levels: b.structure.sr_levels.slice(0, 4),
      last_swing_high: b.structure.last_swing_high, last_swing_low: b.structure.last_swing_low,
      open_fvgs: b.structure.fvgs.filter((f) => f.mitigated_index === null).slice(-3),
    },
    momentum: {
      definition: b.momentum.definition, classification: b.momentum.classification, reason: b.momentum.reason,
      last_leg: b.momentum.last_leg, current_leg: b.momentum.current_leg,
      last_vs_previous_slope_ratio: b.momentum.last_vs_previous_slope_ratio,
      last_vs_previous_size_ratio: b.momentum.last_vs_previous_size_ratio,
    },
    divergence: {
      spec_status: b.divergence.spec_status, indicator: b.divergence.indicator, unsupported: b.divergence.unsupported,
      events: b.divergence.events.slice(-2), note: "technical evidence (RAW_1:891/892/912); not a reversal signal, no confidence",
    },
    stats: b.stats,
    stats_basis: p.stats_basis,
    stats_fetched_ms: p.stats_fetched_ms,
  };
}

/* ---------------------------------------------------------------- health */
export interface ProbeResult {
  state: AiHealthState;
  online: boolean;
  latency_ms: number | null;
  models_count: number | null;
  model_available: boolean | null;
  probed_at_ms: number;
  error: string | null;
}

const probeCache = new Map<string, ProbeResult>();
const PROBE_TTL_MS = 15_000;

function providerConfig(id: "ollama" | "openai"): { base: string; key: string; model: string } {
  return id === "ollama"
    ? { base: OLLAMA_URL.replace(/\/+$/, ""), key: "", model: AI_OLLAMA_MODEL }
    : { base: OPENAI_BASE_URL.replace(/\/+$/, ""), key: OPENAI_API_KEY, model: AI_OPENAI_MODEL };
}

function isConfigured(id: "ollama" | "openai"): boolean {
  const { base, key } = providerConfig(id);
  return id === "ollama" ? base.length > 0 : base.length > 0 && key.length > 0;
}

/**
 * Provider credential access for server-side callers outside this module
 * (e.g. the AI Clone conversation route). Returned values are for building
 * the Authorization header only — keys are never serialized into responses.
 */
export function llmProviderAuth(id: "ollama" | "openai"): { base: string; key: string; model: string } {
  return providerConfig(id);
}

/**
 * Real network probe: list the provider catalogue and check the configured
 * model is actually offered. No claim is made without a measured response.
 * Secrets are only used to build the Authorization header — never returned.
 */
export async function probeProviderDetailed(id: "ollama" | "openai"): Promise<ProbeResult> {
  const cached = probeCache.get(id);
  if (cached && Date.now() - cached.probed_at_ms < PROBE_TTL_MS) return cached;

  const { base, key, model } = providerConfig(id);
  if (!isConfigured(id)) {
    const r: ProbeResult = { state: "NOT_CONFIGURED", online: false, latency_ms: null, models_count: null, model_available: null, probed_at_ms: Date.now(), error: null };
    probeCache.set(id, r);
    return r;
  }

  // Ollama exposes the OpenAI-compat surface under /v1; OPENAI_BASE_URL already includes it.
  const url = id === "ollama" ? `${base}/v1/models` : `${base}/models`;
  const started = Date.now();
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 6000);
  try {
    const res = await fetch(url, {
      headers: key ? { Authorization: `Bearer ${key}` } : {},
      signal: ctrl.signal,
      cache: "no-store",
    });
    const latency_ms = Date.now() - started;
    if (!res.ok) {
      const r: ProbeResult = { state: "ERROR", online: false, latency_ms, models_count: null, model_available: null, probed_at_ms: Date.now(), error: `catalogue HTTP ${res.status}` };
      probeCache.set(id, r);
      return r;
    }
    const body = (await res.json()) as { data?: { id?: unknown }[] };
    const ids = Array.isArray(body.data) ? body.data.map((m) => String(m?.id ?? "")) : [];
    const model_available = ids.length > 0 ? ids.includes(model) : null;
    const r: ProbeResult = {
      state: model_available === false ? "DEGRADED" : "ONLINE",
      online: true,
      latency_ms,
      models_count: ids.length,
      model_available,
      probed_at_ms: Date.now(),
      error: model_available === false ? `configured model "${model}" not in provider catalogue (${ids.length} models offered)` : null,
    };
    probeCache.set(id, r);
    return r;
  } catch (err) {
    const msg = err instanceof Error ? (err.name === "AbortError" ? "probe timeout after 6000ms" : err.message) : String(err);
    const r: ProbeResult = { state: "ERROR", online: false, latency_ms: Date.now() - started, models_count: null, model_available: null, probed_at_ms: Date.now(), error: msg };
    probeCache.set(id, r);
    return r;
  } finally {
    clearTimeout(timer);
  }
}

/** Boolean shim kept for existing call sites (router gating). */
export async function probeProvider(id: "ollama" | "openai"): Promise<boolean> {
  return (await probeProviderDetailed(id)).online;
}

export async function providerStatuses(): Promise<ProviderStatusRow[]> {
  const [ollama, openai] = await Promise.all([probeProviderDetailed("ollama"), probeProviderDetailed("openai")]);
  const row = (id: "ollama" | "openai", p: ProbeResult): ProviderStatusRow => ({
    id,
    configured: isConfigured(id),
    online: p.state === "NOT_CONFIGURED" ? null : p.online,
    state: p.state,
    latency_ms: p.latency_ms,
    model: isConfigured(id) ? providerConfig(id).model : null,
    model_available: p.model_available,
    models_count: p.models_count,
    probed_at_ms: p.state === "NOT_CONFIGURED" ? null : p.probed_at_ms,
    error: p.error,
  });
  return [
    { id: "heuristic", configured: true, online: true, state: "ONLINE", latency_ms: 0, model: "heuristic-v1", model_available: true, models_count: 1, probed_at_ms: Date.now(), error: null },
    row("ollama", ollama),
    row("openai", openai),
  ];
}
